# Generated by Django 4.2 on 2023-04-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moisture_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moisturedata',
            options={'verbose_name_plural': 'Moisture Data'},
        ),
    ]
